// Brand Dossier — standalone report page for a single restaurant chain
// Route: /brand/:name (e.g., /brand/kfc)
// Vertical scroll report: Executive Summary → Data Pipeline → Top Locations → Income → Competitors

import { useMemo } from "react"
import { useParams, Navigate } from "react-router-dom"
import { CountryProvider } from "@/contexts/CountryContext"
import { useCountryData } from "@/hooks/useCountryData"
import { useBrandDossier } from "@/hooks/useBrandDossier"
import { DossierHeader, ExecutiveSummarySection, DataPipelineSection, IncomeAffinitySection } from "@/components/dossier/DossierSections"
import DossierLocations from "@/components/dossier/DossierLocations"
import { MethodologySection, SourceRibbon } from "@/components/explorer/opportunities/ExecutiveBrief"

function BrandDossierContent({ brandKey }: { readonly brandKey: string }) {
  const dossier = useBrandDossier(brandKey)

  if (!dossier) return <Navigate to="/explorer" replace />

  return (
    <div className="min-h-screen bg-surface-deep text-foreground">
      <div className="max-w-[900px] mx-auto px-6 py-10 space-y-10">
        <DossierHeader
          brand={dossier.brand}
          brandColor={dossier.brandColor}
          brandIcon={dossier.brandIcon}
          affinity={dossier.affinity}
          idealDecileRange={dossier.idealDecileRange}
        />

        <ExecutiveSummarySection
          stationCount={dossier.stationCount}
          avgBrandScore={dossier.avgBrandScore}
          affinityMatchRate={dossier.affinityMatchRate}
          idealDecileRange={dossier.idealDecileRange}
          topStationName={dossier.topStations[0]?.stationName ?? "—"}
          topStationScore={dossier.topStations[0]?.score ?? 0}
          strategicThesis={dossier.strategicThesis}
          topCompetitor={dossier.topCompetitor}
          stationCountTotal={dossier.stationCount}
          brand={dossier.brand}
        />

        <DataPipelineSection />

        <DossierLocations
          stations={dossier.topStations}
          brand={dossier.brand}
          brandColor={dossier.brandColor}
        />

        <IncomeAffinitySection
          regionData={dossier.regionAffinityData}
          brandColor={dossier.brandColor}
          idealDecileRange={dossier.idealDecileRange}
          brand={dossier.brand}
        />

        {/* Competitor Landscape */}
        {dossier.competitorLandscape.length > 0 && (
          <section className="space-y-4">
            <h2 className="text-xl font-bold text-foreground">Competitor Landscape</h2>
            <p className="text-sm text-muted-foreground">
              Which brands are already present at {dossier.brand}'s whitespace stations — validating commercial demand.
            </p>
            <div className="space-y-2">
              {dossier.competitorLandscape.map((comp) => (
                <div key={comp.brand} className="flex items-center gap-3 bg-surface-1 border border-border rounded-lg px-4 py-3">
                  <div className="w-3 h-3 rounded-full shrink-0" style={{ backgroundColor: comp.brandColor }} />
                  <span className="text-sm font-semibold text-foreground w-24">{comp.brand}</span>
                  <div className="flex-1 h-2 bg-surface-2 rounded-full overflow-hidden">
                    <div
                      className="h-full rounded-full transition-all"
                      style={{ width: `${comp.overlapPercent}%`, backgroundColor: comp.brandColor }}
                    />
                  </div>
                  <span className="text-sm text-foreground tabular-nums w-20 text-right">
                    {comp.overlapCount}/{dossier.stationCount}
                  </span>
                  <span className="text-xs text-muted-foreground w-12 text-right">{comp.overlapPercent}%</span>
                </div>
              ))}
            </div>
            {dossier.topCompetitor && (
              <p className="text-xs text-muted-foreground leading-relaxed">
                {dossier.topCompetitor.brand} presence at {dossier.topCompetitor.overlapCount} of {dossier.stationCount} whitespace stations confirms commercial viability — where they succeed, {dossier.brand} can follow.
              </p>
            )}
          </section>
        )}

        {/* Methodology + Sources */}
        <section className="space-y-4">
          <MethodologySection />
          <SourceRibbon />
          <p className="text-[10px] text-muted-foreground/50 text-center pt-4">
            Generated by Getplace Intelligence Engine
          </p>
        </section>
      </div>
    </div>
  )
}

// Slug-to-brand mapping (case-insensitive URL)
function useBrandSlugResolver() {
  const { config } = useCountryData("uk")
  return useMemo(
    () => Object.keys(config.brands).reduce(
      (acc, key) => ({ ...acc, [key.toLowerCase()]: key }),
      {} as Record<string, string>,
    ),
    [config.brands],
  )
}

const BrandDossier = () => {
  const { name } = useParams<{ name: string }>()
  const { config, isLoading } = useCountryData("uk")
  const slugMap = useBrandSlugResolver()

  const brandKey = name ? slugMap[name.toLowerCase()] : undefined

  if (isLoading) {
    return (
      <div className="min-h-screen bg-surface-deep flex items-center justify-center">
        <div className="text-muted-foreground text-sm">Loading...</div>
      </div>
    )
  }

  if (!brandKey) {
    return <Navigate to="/explorer" replace />
  }

  return (
    <CountryProvider config={config}>
      <BrandDossierContent brandKey={brandKey} />
    </CountryProvider>
  )
}

export default BrandDossier
