#!/usr/bin/env python3
"""
Compute bus stop density around each rail station as a pedestrian traffic proxy.
High bus stop density near a station = busy pedestrian area = more potential customers.

Input: NaPTAN CSV (415K bus stops) + station-data.ts locations
Output: Enriches station-data.ts with busStopCount800m field
"""

import csv
import json
import math
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "src" / "data" / "Data for assignment"
EXT_DIR = DATA_DIR / "external"
OUT_DIR = ROOT / "src" / "data"


def haversine_km(lat1, lon1, lat2, lon2):
    R = 6371
    dlat = math.radians(lat2 - lat1)
    dlon = math.radians(lon2 - lon1)
    a = (math.sin(dlat / 2) ** 2 +
         math.cos(math.radians(lat1)) * math.cos(math.radians(lat2)) *
         math.sin(dlon / 2) ** 2)
    return R * 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))


def load_bus_stops():
    """Load all bus/coach/tram stops from NaPTAN."""
    naptan_file = EXT_DIR / "naptan-stops.csv"
    stops = []
    with open(naptan_file, encoding="utf-8-sig") as f:
        for row in csv.DictReader(f):
            # BCT = bus/coach/tram, BCS = bus station bay, TMU = tram/metro
            if row.get("StopType") not in ("BCT", "BCS", "TMU", "MET"):
                continue
            try:
                lat = float(row["Latitude"])
                lon = float(row["Longitude"])
            except (ValueError, KeyError):
                continue
            stops.append((lat, lon))
    return stops


def count_nearby(center_lat, center_lon, points, radius_km):
    """Count points within radius using bounding-box pre-filter."""
    lat_tol = radius_km / 111.0
    lon_tol = radius_km / (111.0 * math.cos(math.radians(center_lat)))
    count = 0
    for lat, lon in points:
        if abs(lat - center_lat) > lat_tol or abs(lon - center_lon) > lon_tol:
            continue
        if haversine_km(center_lat, center_lon, lat, lon) <= radius_km:
            count += 1
    return count


def load_current_station_data():
    """Parse existing station-data.ts to get station locations."""
    station_file = OUT_DIR / "station-data.ts"
    content = station_file.read_text()

    stations = []
    # Parse each record line
    for match in re.finditer(
        r"name:\s*'([^']*)',\s*lat:\s*([0-9.-]+),\s*lon:\s*([0-9.-]+),\s*"
        r"region:\s*'([^']*)',\s*annualEntries:\s*(\d+),\s*"
        r"qsrCount400m:\s*(\d+),\s*qsrCount800m:\s*(\d+),\s*"
        r"qsrCount1500m:\s*(\d+),\s*"
        r"brandCounts800m:\s*\{([^}]*)\},\s*"
        r"footfallRatio:\s*(\d+)",
        content,
    ):
        brand_counts_str = match.group(9)
        brand_counts = {}
        for bc in re.finditer(r"(\w+):\s*(\d+)", brand_counts_str):
            brand_counts[bc.group(1)] = int(bc.group(2))

        stations.append({
            "name": match.group(1),
            "lat": float(match.group(2)),
            "lon": float(match.group(3)),
            "region": match.group(4),
            "annualEntries": int(match.group(5)),
            "qsrCount400m": int(match.group(6)),
            "qsrCount800m": int(match.group(7)),
            "qsrCount1500m": int(match.group(8)),
            "brandCounts800m": brand_counts,
            "footfallRatio": int(match.group(10)),
        })

    return stations


def escape_ts_string(s):
    return s.replace("\\", "\\\\").replace("'", "\\'").replace("\n", " ").replace("\r", "")


def write_enriched_station_data(stations):
    """Rewrite station-data.ts with busStopCount800m field."""
    all_brands = list(stations[0]["brandCounts800m"].keys()) if stations else []

    lines = []
    lines.append("// UK rail station data with QSR proximity and bus stop density metrics")
    lines.append("// Sources: ORR Station Usage + NaPTAN (OGL v3.0)")
    lines.append("// Generated by scripts/convert-stations.py + convert-bus-density.py")
    lines.append("")
    lines.append("export interface StationRecord {")
    lines.append("  readonly name: string")
    lines.append("  readonly lat: number")
    lines.append("  readonly lon: number")
    lines.append("  readonly region: string")
    lines.append("  readonly annualEntries: number")
    lines.append("  readonly qsrCount400m: number")
    lines.append("  readonly qsrCount800m: number")
    lines.append("  readonly qsrCount1500m: number")
    lines.append("  readonly brandCounts800m: Readonly<Record<string, number>>")
    lines.append("  readonly footfallRatio: number")
    lines.append("  readonly busStopCount800m: number")
    lines.append("}")
    lines.append("")
    lines.append("export const STATION_DATA: readonly StationRecord[] = [")

    for rec in stations:
        brand_parts = ", ".join(
            f"{b}: {rec['brandCounts800m'].get(b, 0)}" for b in all_brands
        )
        name_esc = escape_ts_string(rec["name"])
        region_esc = escape_ts_string(rec["region"])
        lines.append(
            f"  {{ name: '{name_esc}', lat: {rec['lat']}, lon: {rec['lon']}, "
            f"region: '{region_esc}', annualEntries: {rec['annualEntries']}, "
            f"qsrCount400m: {rec['qsrCount400m']}, qsrCount800m: {rec['qsrCount800m']}, "
            f"qsrCount1500m: {rec['qsrCount1500m']}, "
            f"brandCounts800m: {{ {brand_parts} }}, "
            f"footfallRatio: {rec['footfallRatio']}, "
            f"busStopCount800m: {rec['busStopCount800m']} }},"
        )

    lines.append("] as const")
    lines.append("")

    out_path = OUT_DIR / "station-data.ts"
    with open(out_path, "w") as f:
        f.write("\n".join(lines))
    print(f"  Written {out_path}")


def main():
    print("Loading bus stops from NaPTAN...")
    bus_stops = load_bus_stops()
    print(f"  Loaded {len(bus_stops):,} bus/tram stops")

    print("Loading current station data...")
    stations = load_current_station_data()
    print(f"  Loaded {len(stations)} stations")

    print("Computing bus stop density for each station...")
    for i, station in enumerate(stations):
        if (i + 1) % 200 == 0:
            print(f"  Processing {i + 1}/{len(stations)}...")
        station["busStopCount800m"] = count_nearby(
            station["lat"], station["lon"], bus_stops, 0.8
        )

    # Stats
    bus_counts = [s["busStopCount800m"] for s in stations]
    print(f"\n  Bus stop density stats:")
    print(f"    Min: {min(bus_counts)}, Max: {max(bus_counts)}, "
          f"Avg: {sum(bus_counts)/len(bus_counts):.1f}, "
          f"Median: {sorted(bus_counts)[len(bus_counts)//2]}")

    # Top 10 by bus stop density
    top = sorted(stations, key=lambda s: -s["busStopCount800m"])[:10]
    print(f"\n  Top 10 by bus stop density:")
    for s in top:
        print(f"    {s['busStopCount800m']:>3} stops  {s['annualEntries']:>12,} pax  {s['name']}")

    print("\nWriting enriched station-data.ts...")
    write_enriched_station_data(stations)
    print("Done!")


if __name__ == "__main__":
    main()
