#!/usr/bin/env python3
"""
Enrich station-data.ts with workday workforce population from Census 2021 WP001.
For each station, sums workplace population of all MSOAs within 1.5km radius.

Sources:
  - WP001_msoa.csv: Census 2021 workplace population per MSOA
  - msoa-centroids.csv: Population-weighted centroids (WGS84)
  - station-data.ts: Existing station records (parsed via regex)

Output: Rewrites station-data.ts with new `workplacePop1500m` field.
"""

import csv
import re
import math
import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.dirname(SCRIPT_DIR)
EXT_DIR = os.path.join(ROOT_DIR, "src", "data", "Data for assignment", "external")
STATION_FILE = os.path.join(ROOT_DIR, "src", "data", "station-data.ts")

RADIUS_KM = 1.5
EARTH_RADIUS_KM = 6371.0


def haversine(lat1, lon1, lat2, lon2):
    """Great-circle distance in km."""
    dlat = math.radians(lat2 - lat1)
    dlon = math.radians(lon2 - lon1)
    a = (math.sin(dlat / 2) ** 2 +
         math.cos(math.radians(lat1)) * math.cos(math.radians(lat2)) *
         math.sin(dlon / 2) ** 2)
    return 2 * EARTH_RADIUS_KM * math.asin(math.sqrt(a))


def load_workplace_pop():
    """Load WP001 MSOA workplace population counts."""
    path = os.path.join(EXT_DIR, "WP001_msoa.csv")
    pop = {}
    with open(path, "r", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        for row in reader:
            code = row["Middle layer Super Output Areas Code"].strip()
            count = int(row["Count"].strip())
            pop[code] = count
    print(f"  Loaded {len(pop)} MSOA workplace population records")
    return pop


def load_msoa_centroids():
    """Load MSOA population-weighted centroids (WGS84)."""
    path = os.path.join(EXT_DIR, "msoa-centroids.csv")
    centroids = []
    with open(path, "r", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        for row in reader:
            lon = float(row["X"].strip())
            lat = float(row["Y"].strip())
            code = row["MSOA21CD"].strip()
            centroids.append((code, lat, lon))
    print(f"  Loaded {len(centroids)} MSOA centroids")
    return centroids


def build_msoa_points(pop, centroids):
    """Combine population with coordinates. Only include MSOAs with population > 0."""
    points = []
    for code, lat, lon in centroids:
        count = pop.get(code, 0)
        if count > 0:
            points.append((lat, lon, count))
    print(f"  Combined: {len(points)} MSOAs with workplace population and coordinates")
    return points


def count_workplace_pop_in_radius(station_lat, station_lon, msoa_points, radius_km):
    """Sum workplace population of all MSOAs whose centroids are within radius."""
    # Bounding box pre-filter (approx 0.009 deg/km lat, 0.015 deg/km lon at UK latitudes)
    lat_tol = radius_km * 0.009
    lon_tol = radius_km * 0.015
    total = 0
    for lat, lon, count in msoa_points:
        if abs(lat - station_lat) > lat_tol:
            continue
        if abs(lon - station_lon) > lon_tol:
            continue
        if haversine(station_lat, station_lon, lat, lon) <= radius_km:
            total += count
    return total


def parse_stations(content):
    """Parse station records from TypeScript file (single-quoted, single-line records)."""
    pattern = re.compile(
        r"""\{\s*name:\s*'([^']+)',\s*lat:\s*([\d.-]+),\s*lon:\s*([\d.-]+),\s*"""
        r"""region:\s*'([^']+)',\s*annualEntries:\s*(\d+),\s*"""
        r"""qsrCount400m:\s*(\d+),\s*qsrCount800m:\s*(\d+),\s*qsrCount1500m:\s*(\d+),\s*"""
        r"""brandCounts800m:\s*(\{[^}]*\}),\s*"""
        r"""footfallRatio:\s*([\d.]+),\s*"""
        r"""busStopCount800m:\s*(\d+)"""
        r"""(?:,\s*workplacePop1500m:\s*(\d+))?\s*\}"""
    )
    stations = []
    for m in pattern.finditer(content):
        stations.append({
            "name": m.group(1),
            "lat": float(m.group(2)),
            "lon": float(m.group(3)),
            "region": m.group(4),
            "annualEntries": int(m.group(5)),
            "qsrCount400m": int(m.group(6)),
            "qsrCount800m": int(m.group(7)),
            "qsrCount1500m": int(m.group(8)),
            "brandCounts800m": m.group(9),
            "footfallRatio": float(m.group(10)),
            "busStopCount800m": int(m.group(11)),
        })
    return stations


def generate_ts(stations):
    """Generate TypeScript file content."""
    lines = [
        '// UK rail station data enriched with QSR proximity, bus density, and workplace population',
        '// Sources: ORR 2024-25, NaPTAN, Getplace brand data, Census 2021 WP001',
        '// Generated by scripts/convert-stations.py + convert-bus-density.py + convert-workplace-pop.py',
        '',
        'export interface StationRecord {',
        '  readonly name: string',
        '  readonly lat: number',
        '  readonly lon: number',
        '  readonly region: string',
        '  readonly annualEntries: number',
        '  readonly qsrCount400m: number',
        '  readonly qsrCount800m: number',
        '  readonly qsrCount1500m: number',
        '  readonly brandCounts800m: Readonly<Record<string, number>>',
        '  readonly footfallRatio: number',
        '  readonly busStopCount800m: number',
        '  readonly workplacePop1500m: number',
        '}',
        '',
        'export const STATION_DATA: readonly StationRecord[] = [',
    ]

    for s in stations:
        lines.append(
            f"  {{ name: '{s['name']}', lat: {s['lat']}, lon: {s['lon']}, "
            f"region: '{s['region']}', annualEntries: {s['annualEntries']}, "
            f"qsrCount400m: {s['qsrCount400m']}, qsrCount800m: {s['qsrCount800m']}, "
            f"qsrCount1500m: {s['qsrCount1500m']}, "
            f"brandCounts800m: {s['brandCounts800m']}, "
            f"footfallRatio: {s['footfallRatio']}, "
            f"busStopCount800m: {s['busStopCount800m']}, "
            f"workplacePop1500m: {s['workplacePop1500m']} }},"
        )

    lines.append('] as const')
    lines.append('')
    return '\n'.join(lines)


def main():
    print("=== Enriching station data with Census 2021 Workplace Population ===")
    print()

    # Load data
    print("Loading workplace population...")
    pop = load_workplace_pop()
    centroids = load_msoa_centroids()
    msoa_points = build_msoa_points(pop, centroids)

    # Parse existing stations
    print(f"\nParsing stations from {STATION_FILE}...")
    with open(STATION_FILE, "r", encoding="utf-8") as f:
        content = f.read()
    stations = parse_stations(content)
    print(f"  Parsed {len(stations)} stations")

    # Compute workplace population for each station
    print(f"\nComputing workplace population within {RADIUS_KM}km for each station...")
    total_wp = 0
    max_wp = 0
    max_wp_station = ""
    for i, s in enumerate(stations):
        wp = count_workplace_pop_in_radius(s["lat"], s["lon"], msoa_points, RADIUS_KM)
        s["workplacePop1500m"] = wp
        total_wp += wp
        if wp > max_wp:
            max_wp = wp
            max_wp_station = s["name"]
        if (i + 1) % 500 == 0:
            print(f"  Processed {i + 1}/{len(stations)} stations...")

    avg_wp = total_wp // len(stations) if stations else 0
    print(f"\n  Stations with workplace pop > 0: {sum(1 for s in stations if s['workplacePop1500m'] > 0)}")
    print(f"  Average workplace pop: {avg_wp:,}")
    print(f"  Max: {max_wp_station} = {max_wp:,}")

    # Write output
    print(f"\nWriting enriched data to {STATION_FILE}...")
    output = generate_ts(stations)
    with open(STATION_FILE, "w", encoding="utf-8") as f:
        f.write(output)
    print(f"  Written {len(stations)} stations with workplacePop1500m field")
    print("\n=== Done ===")


if __name__ == "__main__":
    main()
