#!/usr/bin/env python3
"""
Generate workplace population heatmap data from WP001 (Census 2021) + MSOA centroids.

Joins WP001_msoa.csv (workplace population per MSOA) with msoa-centroids.csv (lat/lon).
Output: src/data/workplace-pop-data.ts — compact [lat, lon, count] tuples.

Sources:
  - WP001: Census 2021 Workplace Population (ONS)
  - Centroids: MSOA 2021 population-weighted centroids (ONS)
"""

import csv
import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.dirname(SCRIPT_DIR)
EXT_DIR = os.path.join(ROOT_DIR, "src", "data", "Data for assignment", "external")
OUT_FILE = os.path.join(ROOT_DIR, "src", "data", "workplace-pop-data.ts")


def main():
    print("=== Generating workplace population heatmap data ===\n")

    # 1. Load MSOA centroids (X=lon, Y=lat)
    centroids_path = os.path.join(EXT_DIR, "msoa-centroids.csv")
    centroids = {}
    with open(centroids_path, "r", encoding="utf-8-sig") as f:
        for row in csv.DictReader(f):
            code = row["MSOA21CD"].strip()
            lon = float(row["X"])
            lat = float(row["Y"])
            centroids[code] = (round(lat, 4), round(lon, 4))
    print(f"  Centroids loaded: {len(centroids)}")

    # 2. Load WP001 workplace population
    wp_path = os.path.join(EXT_DIR, "WP001_msoa.csv")
    wp_data = {}
    with open(wp_path, "r", encoding="utf-8-sig") as f:
        for row in csv.DictReader(f):
            code = row["Middle layer Super Output Areas Code"].strip()
            count = int(row["Count"])
            wp_data[code] = count
    print(f"  WP001 records: {len(wp_data)}")

    # 3. Join
    points = []
    matched = 0
    no_centroid = 0
    for code, count in wp_data.items():
        if count <= 0:
            continue
        if code in centroids:
            lat, lon = centroids[code]
            points.append((lat, lon, count))
            matched += 1
        else:
            no_centroid += 1

    print(f"  Matched: {matched}, no centroid: {no_centroid}")
    counts = [p[2] for p in points]
    print(f"  Count range: {min(counts):,} - {max(counts):,}")

    # 4. Output TypeScript
    print(f"\nWriting {len(points)} points to {OUT_FILE}...")
    lines = [
        "// MSOA workplace population for people density heatmap",
        "// Source: Census 2021 WP001 + MSOA 2021 centroids",
        "// Generated by scripts/convert-workplace-heatmap.py",
        "// Each tuple: [lat, lon, workplacePopulation]",
        "",
        "export const WORKPLACE_POP: readonly (readonly [number, number, number])[] = [",
    ]
    for lat, lon, count in points:
        lines.append(f"  [{lat},{lon},{count}],")
    lines.append("] as const")
    lines.append("")

    with open(OUT_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    size_kb = os.path.getsize(OUT_FILE) / 1024
    print(f"  File size: {size_kb:.0f} KB")
    print("\n=== Done ===")


if __name__ == "__main__":
    main()
