// UK region demographic data from deprivation indices across 4 nations
// Sources: IMD 2025 (England), WIMD 2025 (Wales), SIMD 2020v2 (Scotland), NIMDM 2017 (N. Ireland)
// All data under Open Government Licence v3.0
// Generated by scripts/convert-demographics.py

export interface RegionDemographics {
  readonly region: string
  readonly avgIncomeScore: number
  readonly avgEmploymentScore: number
  readonly medianIncomeDecile: number
  readonly avgImdScore: number
  readonly lsoaCount: number
  readonly deprivationSource: string
  readonly microAreaLabel: string
}

export const REGION_DEMOGRAPHICS: readonly RegionDemographics[] = [
  { region: 'North East (England)', avgIncomeScore: 0.2740, avgEmploymentScore: 0.1842, medianIncomeDecile: 4, avgImdScore: 28.45, lsoaCount: 1762, deprivationSource: 'IMD 2025', microAreaLabel: 'LSOAs' },
  { region: 'North West (England)', avgIncomeScore: 0.2502, avgEmploymentScore: 0.1595, medianIncomeDecile: 5, avgImdScore: 25.71, lsoaCount: 5115, deprivationSource: 'IMD 2025', microAreaLabel: 'LSOAs' },
  { region: 'Yorkshire and The Humber', avgIncomeScore: 0.2464, avgEmploymentScore: 0.1506, medianIncomeDecile: 5, avgImdScore: 24.86, lsoaCount: 3321, deprivationSource: 'IMD 2025', microAreaLabel: 'LSOAs' },
  { region: 'East Midlands (England)', avgIncomeScore: 0.2152, avgEmploymentScore: 0.1315, medianIncomeDecile: 5, avgImdScore: 20.76, lsoaCount: 2778, deprivationSource: 'IMD 2025', microAreaLabel: 'LSOAs' },
  { region: 'West Midlands (England)', avgIncomeScore: 0.2691, avgEmploymentScore: 0.1542, medianIncomeDecile: 4, avgImdScore: 24.90, lsoaCount: 3408, deprivationSource: 'IMD 2025', microAreaLabel: 'LSOAs' },
  { region: 'East (England)', avgIncomeScore: 0.1936, avgEmploymentScore: 0.1128, medianIncomeDecile: 6, avgImdScore: 17.83, lsoaCount: 3593, deprivationSource: 'IMD 2025', microAreaLabel: 'LSOAs' },
  { region: 'London', avgIncomeScore: 0.2726, avgEmploymentScore: 0.1293, medianIncomeDecile: 3, avgImdScore: 22.51, lsoaCount: 5210, deprivationSource: 'IMD 2025', microAreaLabel: 'LSOAs' },
  { region: 'South East (England)', avgIncomeScore: 0.1743, avgEmploymentScore: 0.1032, medianIncomeDecile: 6, avgImdScore: 15.94, lsoaCount: 5217, deprivationSource: 'IMD 2025', microAreaLabel: 'LSOAs' },
  { region: 'South West (England)', avgIncomeScore: 0.1837, avgEmploymentScore: 0.1162, medianIncomeDecile: 6, avgImdScore: 17.96, lsoaCount: 3351, deprivationSource: 'IMD 2025', microAreaLabel: 'LSOAs' },
  { region: 'Wales', avgIncomeScore: 0.2383, avgEmploymentScore: 0.2383, medianIncomeDecile: 5, avgImdScore: 21.72, lsoaCount: 1917, deprivationSource: 'WIMD 2025', microAreaLabel: 'LSOAs' },
  { region: 'Scotland', avgIncomeScore: 0.1229, avgEmploymentScore: 0.0956, medianIncomeDecile: 8, avgImdScore: 50.00, lsoaCount: 6973, deprivationSource: 'SIMD 2020', microAreaLabel: 'Data Zones' },
  { region: 'Northern Ireland', avgIncomeScore: 0.1300, avgEmploymentScore: 0.2118, medianIncomeDecile: 7, avgImdScore: 49.94, lsoaCount: 890, deprivationSource: 'NIMDM 2017', microAreaLabel: 'SOAs' },
] as const
